### PR TITLE
Setup script

### PR DESCRIPTION
**Pull request by wesbarnett**
Related to #7 . This creates a setup.py script so that a user can do "python setup.py install" in order to install the script as well as it's dependencies. I had to change the directory hiearchy some for this to work smoothly, although there could be a way to keep it the same with the right commands in setup.py. It also creates a link to the script so someone can just call "alchemical_analysis <args>" from the command line. This would also be the first step in putting the package in [PyPI](https://pypi.python.org/pypi) (pymbar is there too). There are several things you should change in setup.py as far as the metadata (version number, etc.).

### CODE REVIEW

**Comment by davidlmobley** [comment]
Thanks. I'll review this soon - I'd not created an issue yet for this, but this is something I had wanted to do, as I'd run into the same problem. Longer-term, I also want to make a conda recipe for it. We very much appreciate the help with this - above and beyond the call of duty, from my perspective. Pavel is on a time crunch towards graduating so he doesn't have much time to contribute right now.

**Comment by wesbarnett** [comment]
Hey not a problem. I'm happy to contribute when possible. I saw the "help wanted" for #7 so thought I would give it a shot. This does need more thorough testing as just today I ran it with some different flags and it gave an error that a variable wasn't global (I'll add to the pull request later for this case). It has to do with creating that main() function so that variables inside it are no longer seen as global. I'm not sure if there's a better way to do that other than tracking down all the variables that need to be global and explicitly listing all of them at the beginning. I made the main() function for the "entry_point" feature of setup.py.

**Comment by davidlmobley** [comment]
I tried all options which apply to my dataset and didn't run into any further global variable problems, so I *think* this is ready to merge if you don't have any other outstanding issues. LMK. (I did also in the process find a bug with the overlap matrix and created a separate issue for it).

**Comment by wesbarnett** [comment]
The only other thing you might want to do before merging is double-check / update the metadata in setup.py (especially version number).

**Pull request merged**
