### PR TITLE
Fix setup.py so only main executable goes in bin and put version check in setup.py

### PR DESCRIPTION
**Pull request by wesbarnett**
The previous implementation had all scripts in the package (parser_gromacs,py, etc.) placed in the bin directory (i.e., /usr/bin or /usr/local/bin). This fixes that behavior.

### CODE REVIEW

**Comment by wesbarnett** [comment]
Also I can remove all the extra comments, but I didn't know if those were helpful to keep there

**Comment by davidlmobley** [comment]
Ah, excellent. I'm not used to using a setup.py (OK, haven't done much code development of anything significant) so it didn't occur to me to put the version check in there. 

Is this ready to merge? 

>Also I can remove all the extra comments, but I didn't know if those were helpful to keep there

I also don't have any problem with the current level of commenting.

**Comment by wesbarnett** [comment]
It's ready to merge now.

**Comment by davidlmobley** [comment]
@wesbarnett - this broke something for me, and I'm not totally sure what, so I had to revert the merge. Here's what I currently get after installing it:

```
alchemical_analysis -h
Traceback (most recent call last):
  File "/Users/dmobley/anaconda/bin/alchemical_analysis", line 9, in <module>
    load_entry_point('alchemical-analysis==1.0.2.dev0', 'console_scripts', 'alchemical_analysis')()
  File "/Users/dmobley/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 547, in load_entry_point
  File "/Users/dmobley/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2719, in load_entry_point
  File "/Users/dmobley/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2379, in load
  File "/Users/dmobley/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2385, in resolve
  File "/Users/dmobley/anaconda/bin/alchemical_analysis.py", line 4, in <module>
    __import__('pkg_resources').run_script('alchemical-analysis==1.0.2.dev0', 'alchemical_analysis.py')
  File "/Users/dmobley/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 724, in run_script
  File "/Users/dmobley/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1641, in run_script
pkg_resources.ResolutionError: No script named 'alchemical_analysis.py'
```

It's possibly it's an environment issue of some sort for me...? After reverting, `alchemical_analysis.py -h` works fine.

**Comment by davidlmobley** [comment]
(I'm OK with the general idea, and with the version check going in setup.py, but am ambivalent about the switch from `alchemical_analysis.py` to `alchemical_analysis` and I certainly only want to do it if it actually works.)

**Comment by wesbarnett** [comment]
Without this pull request it is populating the user's bin directory with both `alchemical_analysis.py` and `alchemical_analysis` (plus a few other scripts). So `alchemical_analysis` should work with either one.

I think the issue is that the scripts `unixlike.py`, `parser-gromacs.py`, and `alchemical_analysis.py` are still in the bin directory when you manually upgrade and this somehow confuses the program (something's not in the right spot). To get it to work I had to uninstall and then reinstall again:

    sudo pip uninstall alchemical_analysis
    sudo python setup.py install

**Comment by davidlmobley** [comment]
OK. Er, to save me time git-wrangling, do you mind pulling down master again (I just made another bugfix) and then resubmitting your PR? Since I already merged/closed it, it's not totally obvious to me how I re-awaken it. I could certainly figure it out eventually but you should be able to submit another with just the click of a button, which is a lot faster than waiting for me to figure it out. 

Thanks.

**Comment by wesbarnett** [comment]
PR #77

**Pull request merged**
