### PR TITLE
New parser

### PR DESCRIPTION
**Pull request by halx**
Just to see if this is necessary for a merger.

### CODE REVIEW

**Comment by davidlmobley** [comment]
@halx - also, we recently made some updates to main, so if you could resolve/merge back into your PR that would be great.

**Comment by halx** [comment]
Merged and updated.  You really need to think about abstracting the file
parsers and making them polymorphing.  Your many ifs for the various codes
get messier and messier.

**Comment by davidlmobley** [comment]
This looks good to me, except that we just merged one more CR so can you merge/update again? Then I'll merge your PR. I'll have to look into the polymorphing thing as I have to admit that doesn't mean anything to me at present. (But I agree that the `if` statements are a problem.)

**Comment by halx** [comment]
Done. I'll comment about the polymorphing in another email.  It's fairly
easy to do in your case.

**Comment by davidlmobley** [comment]
Thanks! Merging.

**Pull request merged**
