### PR TITLE
Fix bug from a line introduced/left from previous commit

### PR DESCRIPTION
**Pull request by mrshirts**
Doesn't affect results, but causes a crash for expanded ensemble when the number of files > number of states.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Thanks, @mrshirts .

**Comment by mrshirts** [comment]
Responding to github -> Yes, automated tests for expanded ensemble would have caught this originally . . .

**Comment by davidlmobley** [comment]
Yes, automated tests for anything... :) I haven't had a chance to set up Travis-CI for this repo, nor to design appropriate tests (partly because no one here is working on this code at all at this point...).  I'm hoping as `alchemlyb` comes along we can remedy that.

**Comment by mrshirts** [comment]
I might have @trje3733 eventually set some up, as it will allow us to transition to alchemlyb more easily.  A few other things have higher priority first!

**Pull request merged**
