### PR TITLE
Read in temperature from Gromacs files.

### PR DESCRIPTION
**Pull request by wesbarnett**

### CODE REVIEW

**Comment by davidlmobley** [comment]
@wesbarnett - I'll try and test this on a couple of cases later and hopefully get it merged. Seems reasonable. 

Also, do you happen to know the history on issue #20 ? I haven't used this much recently but as far as I can tell that line has been there for a while, and it's unclear to me why you haven't run into that problem.

One thing I want to do down the line is get automated testing going (via Travis-CI) so that every PR automatically gets tested to make sure it doesn't break anything. But this will take somewhat longer as this is not high priority for us.

**Comment by wesbarnett** [comment]
@davidlmobley not a problem. Thanks for considering this for inclusion.

**Comment by davidlmobley** [comment]
@wesbarnett - any chance that, while you're at it, you could add a check that the temperature is the same across all files? 

Once, we played around with a use case where we might change (i.e. increase to improve sampling) the temperature at intermediate lambda values in a lambda exchange simulation, but this got dropped. This currently wouldn't be handled correctly by alchemical-analysis.py since we assume a single temperature. Possibly we could later generalize to handle that case but in the meantime we probably want to make sure no one does something incorrect accidentally/without checking.

**Comment by davidlmobley** [comment]
@wesbarnett - I tried this out and it worked fine for me (in a case where temperature is not in the xvg files; I don't seem to have one which does have temperature, at least not on hand at present). So aside from the check I just requested I can merge once that's done.

Note though that in the meantime I made two very minor one-line tweaks to the main branch to address issue #20.

**Comment by wesbarnett** [comment]
@davidlmobley I added a check for the temperatures.

**Pull request merged**
